plugins:
  - jekyll-remote-theme

remote_theme: daattali/beautiful-jekyll
theme-dark: auto

title: Portfolio-Webseite von Nadine Bock
description: "Angehende Fachinformatikerin für Systemintegration"

author: Nadine Bock

url: "https://nadinebock.github.io"

navbar-links:
  Über Mich: "/about/"
  Projekte: "/projects/"

avatar: "/assets/HG1.jpg"
